const wordset = [
  {
    title: "주니어 능률 VOCA 기본 1200제",
    template: "swap",
    timelimit: 20,
    test: {
      all: 0,
      step: 10,
    },
    steps: [
      [
        ["fix", "수리하다, 고치다"],
        ["shade", "그늘"],
        ["bury", "묻다, 매장하다"],
        ["cave", "동굴, 굴"],
        ["useful", "쓸모 있는, 유용한"],
        ["dot", "(동그란) 점"],
        ["copy", "복사(본), 복사하다"],
        ["through", "통과하여, 지나서"],
        ["oven", "오븐"],
        ["lend", "빌려주다"],
        ["moment", "순간, 시점, 잠깐, 잠시"],
        ["wing", "날개"],
        ["neighbor", "이웃"],
        ["piece", "조각, 한 개, 한 장"],
        ["still", "아직도, 여전히"],
        ["twin", "쌍둥이, 쌍둥이의"],
        ["pure", "순수한, 맑은, 깨끗한"],
        ["stage", "단계, 시기, 무대"],
        ["at first", "처음에는"],
        ["put on", "~을 입다"]
      ],
      [
        ["war", "전쟁"],
        ["cash", "현금, 현찰"],
        ["advice", "충고, 조언"],
        ["lead", "안내하다, 지도하다, 이끌다"],
        ["perfect", "완벽한, 꼭 알맞은"],
        ["search", "찾다, 수색하다"],
        ["contest", "대회, 콘테스트"],
        ["display", "전시하다, 진열하다"],
        ["tip", "끝, 팁, 봉사료, 조언"],
        ["borrow", "빌리다"],
        ["sharp", "날카로운, 뾰족한"],
        ["machine", "기계"],
        ["trouble", "어려움, 문제"],
        ["roll", "구르다, 굴리다, 두루마리"],
        ["exit", "출구, 나가다, 퇴장하다"],
        ["proud", "자랑스러워하는, 자랑스러운, 거만한"],
        ["flood", "홍수"],
        ["stamp", "우표, 도장"],
        ["at last", "마침내"],
        ["grow up", "자라다, 성장하다"]
      ],
      [
        ["mix", "섞이다, 섞다"],
        ["healthy", "건강한, 건강에 좋은"],
        ["active", "활동적인, 적극적인"],
        ["dig", "파다"],
        ["simple", "간단한, 단순한"],
        ["view", "경치, 전망, 견해, 의견"],
        ["insect", "곤충"],
        ["sleepy", "졸리는"],
        ["root", "뿌리, 근원, 원인"],
        ["total", "총, 전체의, 완전한, 전적인, 합계"],
        ["final", "마지막의, 최후의, 결승"],
        ["scene", "장면, 경치, 풍경"],
        ["prize", "상, 상품"],
        ["nickname", "별명"],
        ["pan", "팬, 프라이팬"],
        ["cartoon", "만화"],
        ["leader", "지도자, 리더"],
        ["coach", "코치, 감독"],
        ["find out", "~을 알아내다"],
        ["be in trouble", "어려움에 처하다"],
      ],
      [
        ["lift", "(들어) 올리다"],
        ["pack", "(짐을) 싸다, 포장하다, 한 갑"],
        ["score", "득점, 점수, 득점하다"],
        ["court", "법정, 법원, 경기장, 코트"],
        ["desert", "사막"],
        ["award", "상, 수여하다, 주다"],
        ["elder", "나이가 더 많은, 노인"],
        ["among", "~ 사이에, ~에 둘러싸여, ~ 중에"],
        ["male", "남성, 수컷"],
        ["finally", "마침내, 결국, 마지막으로"],
        ["sometime", "언젠가"],
        ["rule", "규칙, 규정, 지배하다"],
        ["harmony", "조화, 화합, 화음"],
        ["bark", "짖다"],
        ["crash", "충돌하다, 충돌, 추락"],
        ["nature", "자연, 천성, 본성"],
        ["valley", "계속, 골짜기"],
        ["wonder", "궁금하다, 경탄, 놀라움"],
        ["think up", "~을 생각해내다"],
        ["be famous for", "~로 유명하다"],
      ],
      [
        ["hang", "걸리다, 걸다, 매달리다"],
        ["able", "~할 수 있는, 능력있는"],
        ["pain", "통증, 고통"],
        ["uniform", "제복, 유니폼, 균일한"],
        ["beauty", "아름다움, 미"],
        ["taste", "맛, 맛이 나다"],
        ["shout", "소리치다, 외치다"],
        ["without", "~ 없이, ~하지 않고"],
        ["care", "주의, 보살핌, 상관하다, 신경 쓰다"],
        ["sunlight", "햇빛, 햇살"],
        ["female", "여성, 암컷"],
        ["lower", "아래쪽의, 낮추다, 내리다"],
        ["miss", "놓치다, 빗나가다, 그리워하다"],
        ["exact", "정확한"],
        ["popular", "인기 있는, 대중의, 대중적인"],
        ["regular", "정기적인, 규칙적인, 보통의, 표준적인"],
        ["noisy", "시끄러운"],
        ["dive", "뛰어들다, 다이빙하다"],
        ["before long", "머지않아, 얼마 후에"],
        ["calm down", "진정하다, ~을 진정시키다"],
      ],
      [
        ["pill", "알약, 정제"],
        ["alarm", "경보(기), 자명종, 알람"],
        ["bored", "지루한, 지겨운"],
        ["freeze", "얼다, 얼리다"],
        ["nobody", "아무도 ~않다"],
        ["language", "언어, 말"],
        ["teenager", "십 대"],
        ["usual", "평소의, 보통의"],
        ["chance", "가능성, 기회, 우연"],
        ["hero", "영웅, 주인공"],
        ["curl", "곱슬곱슬하다, 곱슬머리"],
        ["planet", "행성"],
        ["regularly", "정기적으로, 규칙적으로"],
        ["invent", "발명하다"],
        ["smart", "영리한, 똑똑한"],
        ["dead", "죽은"],
        ["soil", "흙, 토양"],
        ["meal", "식사, 끼니, 음식"],
        ["take care", "조심하다"],
        ["because of", "~ 때문에"],
      ],
      [
        ["coin", "동전"],
        ["prepare", "준비하다, 마련하다"],
        ["quite", "꽤, 상당히"],
        ["collect", "모으다, 수집하다"],
        ["main", "주된, 주요한"],
        ["shower", "샤워, 소나기"],
        ["alike", "비슷한, 비슷하게, 마찬가지로"],
        ["blank", "공백의, 빈, 빈칸, 공란"],
        ["freezing", "몹시 추운"],
        ["important", "중요한"],
        ["spicy", "매콤한, 자극적인"],
        ["teenager", "십 대, 십 대의"],
        ["weigh", "무게가 ~이다, 무게를 재다"],
        ["deaf", "귀가 먹은"],
        ["law", "법, 법률"],
        ["rub", "비비다, 문지르다"],
        ["pour", "따르다, 붓다, 쏟아지다, 퍼붓다"],
        ["yet", "아직, 벌써"],
        ["take out", "~을 꺼내다, ~을 데리고 나가다"],
        ["get out of", "나가다, 내리다"],
      ],
      [
        ["skill", "기량, 솜씨, 기술"],
        ["neat", "정돈된, 단정한"],
        ["ache", "아프다, 쑤시다, 아픔, 통증"],
        ["patient", "환자, 참을성 있는"],
        ["elderly", "나이가 지긋한, 연세가 드신"],
        ["mistake", "실수, 잘못"],
        ["channel", "채널"],
        ["during", "~동안 (내내)"],
        ["flour", "밀가루"],
        ["lawyer", "변호사"],
        ["tire", "지치다, 지치게 하다, 타이어"],
        ["bar", "막대기, (창문) 살, 바"],
        ["soldier", "군인, 병사"],
        ["recipe", "요리법, 레시피"],
        ["course", "강의, 강좌, 항로, 방향"],
        ["wallet", "지갑"],
        ["guide", "안내자, 가이드, 안내하다"],
        ["silent", "말이 없는, 침묵하는, 조용한, 고요한"],
        ["fill in", "기입하다, 써넣다, 메우다"],
        ["be different from", "~와 다르다"],
      ],
      [
        ["rail", "철로, 철도, 기차", "1"],
        ["adult", "성인, 어른, 성인의, 다 자란", "1"],
        ["tasty", "맛있는", "1"],
        ["couple", "한 쌍, 두 개, 부부", "1"],
        ["especially", "특히, 특별히, 각별히", "2"],
        ["soap", "비누", "1"],
        ["lonely", "외로운, 쓸쓸한", "1"],
        ["mind", "마음, 정신 / 꺼리다, 싫어하다", "2"],
        ["invention", "발명(품)", "1"],
        ["blind", "눈 먼, 맹인의 / 깨닫지 못하는", "1"],
        ["curly", "곱슬솝슬한", "1"],
        ["stick", "나뭇가지, 막대기 / 채 / 붙다, 붙이다", "2"],
        ["purse", "(여성용) 지갑, 핸드백", "1"],
        ["share", "함께 쓰다, 공유하다 / 나누다", "1"],
        ["design", "디자인하다, 설계하다", "1"],
        ["form", "종류, 유형 / 서식 / 형성하다", "2"],
        ["wild", "야생의", "2"],
        ["gallery", "미술관, 화랑", "1"],
        ["pick up", "~을 집어 들다 / ~를 태우러 가다(오다)", "3"],
        ["help out", "도와주다", "2"],
      ],
      [
        ["chat", "수다를 떨다 / 수다, 담소", "1"],
        ["designer", "디자이너", "1"],
        ["result", "결과 / (~의 결과로) 발생하다, 생기다", "2"],
        ["type", "종류, 유형", "1"],
        ["someday", "(미래의) 언젠가", "1"],
        ["actual", "실제의, 사실의", "1"],
        ["culture", "문화", "1"],
        ["lost", "길을 잃은 / 잃어버린", "1"],
        ["item", "물품, 품목 / 항목, 사항", "1"],
        ["natural", "자연의 / 당연한, 자연스러운 / 타고난", "2"],
        ["secret", "비밀, 비밀의", "1"],
        ["breath", "숨, 호흡", "1"],
        ["excite", "흥분시키다, 들뜨게 하다", "2"],
        ["online", "온라인의", "1"],
        ["garbage", "쓰레기", "1"],
        ["suck", "빨아 먹다 / 빨다", "1"],
        ["prison", "교도소, 감옥", "1"],
        ["flow", "흐름/ 흐르다", "1"],
        ["make noise", "소란을 피우다, 떠들다", "2"],
        ["hand in hand", "서로 손을 잡고", "2"],
      ],
      [
        ["solar", "태양의 / 태양열의", "2"],
        ["captain", "선장, 기장 / 주장", "2"],
        ["dialogue", "대화, 회화", "2"],
        ["fail", "실패하다 / (시험에) 떨어지다", "1"],
        ["actually", "실제로, 정말로", "1"],
        ["special", "특별한", "1"],
        ["tear", "눈물 / 찢어지다, 찢다", "1"],
        ["however", "그런, 그렇지만", "1"],
        ["burn", "타다, 태우다", "1"],
        ["upstairs", "위층에 / 위층", "1"],
        ["living", "살아 있는 / 생활비, 생계 수단", "1"],
        ["report", "보고서 / 보고하다, 발표하다 / 보도하다", "2"],
        ["produce", "생산하다 / 낳다, 일으키다", "2"],
        ["cheer", "환호(성) / 환호하다, 격려하다", "1"],
        ["excited", "신이 난, 흥분한", "1"],
        ["gather", "모이다, 모으다 / 수집하다", "1"],
        ["melt", "녹다, 녹이다", "1"],
        ["straw", "짚, 밀짚 / 빨대", "1"],
        ["take care of", "~을 돌보다", "2"],
        ["not ~ anymore", "더 이상 ~ 않다", "2"],
      ],
      [
        ["save", "구하다 / 저축하다 / 절약하다", "2"],
        ["cause", "원인, ~의 원인이 되다", "2"],
        ["exercise", "운동, 운동하다 / 훈련, 연습", "1"],
        ["member", "회원, 일원", "1"],
        ["press", "누르다 / 신문, 언론", "1"],
        ["serious", "심각한 / 진지한", "1"],
        ["talent", "(타고난) 재능, 재주", "2"],
        ["greet", "맞이하다, 환영하다", "2"],
        ["beat", "때리다, 두드리다 / 이기다", "1"],
        ["stress", "압박 / 강조, 강조하다", "1"],
        ["later", "나중에, 후에 / 더 늦은, 나중의", "1"],
        ["create", "창조하다, 만들다", "1"],
        ["flat", "평평한 / 바람이 빠진", "1"],
        ["return", "돌아가다 / 돌려주다, 반납하다 / 귀환", "1"],
        ["activity", "활동", "1"],
        ["afraid", "두려워하는 / 걱정하는", "1"],
        ["dessert", "후식", "1"],
        ["toothache", "치통", "1"],
        ["in fact", "사실은", "2"],
        ["no longer", "더 이상 ~ 않다", "2"],
      ],
      [
        ["effect", "영향, 결과", "2"],
        ["focus", "집중하다, 집중시키다 / 초점, 중점", "2"],
        ["dictionary", "사전", "1"],
        ["allow", "허락하다, 허용하다", "1"],
        ["print", "인쇄하다 / 출판하다, 발행하다", "1"],
        ["safety", "안전하게, 무사히", "2"],
        ["giant", "거인 / 거대한, 특대의", "1"],
        ["usually", "보통, 대개", "1"],
        ["creative", "창의적인, 창조적인", "1"],
        ["review", "검토(하다) / 평론, 비평 / 복습(하다)", "2"],
        ["kiss", "입맞추다 / 입맞춤", "1"],
        ["strange", "이상한 / 낯선", "1"],
        ["comic", "웃기는 / 희극의 / 만화책", "1"],
        ["mark", "얼룩, 자국 / 표시(하다)", "2"],
        ["shop", "가게, 상점 / 물건을 사다", "1"],
        ["talented", "재능 있는, 유능한", "2"],
        ["bare", "벌거벗은, 날 것의", "2"],
        ["housework", "집안일, 가사", "1"],
        ["at least", "적어도, 최소한", "2"],
        ["pass through", "지나가다, 통과하다 / 겪다, 경험하다", "3"],
      ],
      [
        ["rise", "오르다, 상승하다 / 일어나다 / 뜨다", "1"],
        ["accept", "받아들이다, 수락하다", "1"],
        ["topic", "주제, 화제", "2"],
        ["flight", "여행, 비행 / 항공편, 항공기", "1"],
        ["hunter", "사냥꾼", "1"],
        ["medicine", "약, 약물 / 의학, 의술", "2"],
        ["text", "글, 본문 / 문서", "1"],
        ["boil", "끓다, 끓이다 / 삶다", "1"],
        ["pleasure", "즐거움, 기쁨", "1"],
        ["dirt", "먼지, 때 / 흙", "2"],
        ["everywhere", "모든 곳에, 어디든지", "2"],
        ["sheet", "얇은 천 / 한 장", "1"],
        ["village", "(시골) 마을", "1"],
        ["powerful", "영향력 있는 / 강력한, 효과적인", "2"],
        ["scare", "겁주다, 겁나게 하다", "2"],
        ["step", "(발)걸음 / 조치 / 단계", "1"],
        ["cooking", "요리(하기) / 요리의", "1"],
        ["anger", "화, 분노", "1"],
        ["look up", "찾아보다 / 올려다보다", "2"],
        ["cut ~ into pieces", "~를 여러 조각으로 자르다", "2"],
      ],
      [
        ["own", "자기 자신의 / 소유하다", "1"],
        ["praise", "칭찬하다 / 칭찬, 찬양", "1"],
        ["continue", "계속되다, 계속하다", "1"],
        ["wooden", "나무로 된, 목재의", "1"],
        ["coast", "해안, 연안", "1"],
        ["hike", "도보 여행 (하다)", "1"],
        ["scared", "두려워하는, 겁먹은", "1"],
        ["beyond", "~너머에 / ~를 지나서", "1"],
        ["meeting", "회의", "1"],
        ["danger", "위험(성)", "1"],
        ["traffic", "교통(량)", "1"],
        ["even", "~조차, ~까지, ~도 / 훨씬, 더욱", "1"],
        ["foreign", "외국의", "1"],
        ["lie", "눕다 / 놓여 있다 / 거짓말하다", "1"],
        ["skip", "거르다 / 건너뛰나, 생략하다", "1"],
        ["refuse", "거절하다, 거부하다", "1"],
        ["plate", "접시", "1"],
        ["alive", "살아 있는", "1"],
        ["stay up", "깨어 있다, 안 자다", "1"],
        ["get along with", "~와 잘 지내다", "1"],
      ],
      [
        ["sign", "표지판 / 기미, 조짐 / 서명하다", "1"],
        ["branch", "나뭇가지 / 지점, 지사", "1"],
        ["reach", "도착하다, 도달하다 / 닿다", "1"],
        ["common", "흔한 / 공통의, 공동의", "1"],
        ["path", "길, 오솔길 / 경로, 방향", "1"],
        ["core", "핵심, 중심부 / 핵심적인, 가장 중요한", "1"],
        ["foreigner", "외국인", "1"],
        ["toward", "~ 쪽으로, ~을 향하여", "1"],
        ["vote", "투표하다 / 투표, 표결", "1"],
        ["headache", "두통", "1"],
        ["interest", "흥미, 관심사 / 관심을 끌다", "1"],
        ["match", "경기, 시합 / 성냥 / 어울리다", "1"],
        ["owner", "주인, 소유자", "1"],
        ["scary", "무서운, 두려운", "1"],
        ["aid", "도움 / 원조, 지원", "1"],
        ["tradition", "전통, 관습", "1"],
        ["per", "~당, ~마다", "1"],
        ["wax", "밀랍 / 밀랍을 발라 광을 내다", "1"],
        ["at that time", "그때, 그 당시", "1"],
        ["sooner or later", "조만간, 곧", "1"],
      ],
      [
        ["judge", "판사 / 심판 / 판단하다, 평가하다",],
        ["agree", "동의하다",],
        ["basic", "기본적인, 기초적인 / 기본, 기초",],
        ["drawer", "서랍",],
        ["greenhouse", "온실",],
        ["iron", "철, 쇠 / 다리미",],
        ["tower", "탑",],
        ["either", "어느 한 쪽 / ~도 또한",],
        ["mad", "화가 난 / 미친",],
        ["straight", "똑바로, 곧장 / 곧은, 일직선의",],
        ["record", "기록 / 기록하다",],
        ["solve", "풀다, 해결하다",],
        ["company", "회사 / 동료, 일행",],
        ["nation", "국가, 나라",],
        ["pleased", "기쁜, 만족스러운",],
        ["control", "통제(력), 지배(력) / 통제하다, 지배하다",],
        ["helpful", "도움이 되는, 유익한",],
        ["self", "자신, 자아",],
        ["run out", "(시간, 돈, 기름이) 다 되다, 다 떨어지다",],
        ["after all", "결국, 어쨌든",],
      ],
      [
        ["fry", "튀기다, 볶다",],
        ["habit", "버릇, 습관",],
        ["tax", "세금",],
        ["surprised", "놀란, 놀라는",],
        ["abroad", "해외에, 해외로",],
        ["slide", "미끄러지다 / 미끄럼틀",],
        ["disagree", "동의하지 않다",],
        ["while", "~하는 동안 / ~에 반하여 / 잠깐, 잠시",],
        ["row", "열, 줄",],
        ["festival", "축제",],
        ["aloud", "소리 내어 / 큰 소리로",],
        ["shape", "형태, 모양 / 상태, 몸매",],
        ["tough", "힘든, 어려운 / 강인한, 굳센",],
        ["cafeteria", "구내식당",],
        ["lock", "잠기다, 잠그다 / 자물쇠, 잠금장치",],
        ["bottom", "맨 아래, 바닥 / 맨 아래의",],
        ["product", "생산품, 제품",],
        ["medal", "훈장",],
        ["get to", "~에 도착하다, ~에 이르다",],
        ["come true", "이루어지다, 실현되다",],
      ],
      [
        ["sale", "판매 / 할인 판매"],
        ["metal", "금속"],
        ["complete", "완전한, 완벽한 / 완료하다, 완성하다"],
        ["general", "전반적인 / 일반적인, 일반의 / 장군"],
        ["parade", "행진"],
        ["royal", "왕실의, 왕족의"],
        ["ever", "언젠가, 지금까지 / 결코, 전혀 (부정문)"],
        ["though", "비록 ~이지만"],
        ["direct", "직접적인 / 지휘하다, 안내하다"],
        ["amazing", "놀라운, 굉장한"],
        ["clay", "점토, 찰흙"],
        ["bow", "인사하다, 절하다 / 인사, 절 / 활"],
        ["interview", "면접 / 회견"],
        ["outdoor", "야외의"],
        ["normal", "보통의, 평범한 / 정상적인"],
        ["factory", "공장"],
        ["peer", "또래, 동료 / 집단 "],
        ["sketch", "밑그림"],
        ["after a while", "잠시 후에"],
        ["slow down", "(속도를) 늦추다"],
      ],
      [
        ["base", "맨 아랫부붙, 밑바닥 / 기초, 기반"],
        ["grade", "등급 / 학년 / 성적"],
        ["signal", "신호"],
        ["meaning", "의미, 뜻"],
        ["cover", "덮다 / 다루다, 포함하다"],
        ["awake", "깨어 있는"],
        ["quickly", "빨리, 빠르게"],
        ["trash", "쓰레기"],
        ["protect", "보호하다, 지키다"],
        ["evil", "사악한, 악"],
        ["character", "성격, 성질 / 특징, 특색 / 등장인물"],
        ["friendly", "친절한, 다정한"],
        ["worried", "걱정스러운"],
        ["director", "이사, 임원 / 책임자, 관리자 / 감독"],
        ["sentence", "문장 / 선고, 판결"],
        ["loose", "헐거운, 느슨한 / 헐렁한"],
        ["indoor", "실내(용)의"],
        ["puzzle", "수수께기"],
        ["take away", "~을 치우다"],
        ["have ~ in common", "공통적으로 ~을 가지다"],
      ],
      [
        ["bill", "고지서, 청구서 / 지폐"],
        ["cough", "기침하다 / 기침"],
        ["image", "인상 / 모습"],
        ["national", "국가의, 국가적인 / 국립의, 국영의"],
        ["seed", "씨앗, 종자"],
        ["truth", "진실, 사실"],
        ["mixture", "혼합(물)"],
        ["reuse", "재사용하다"],
        ["discover", "발견하다 / 알게 되다, 깨닫다"],
        ["junk", "쓸모 없는 물건, 쓰레기"],
        ["courage", "용기"],
        ["shine", "빛나다, 반짝이다"],
        ["eastern", "동쪽의, 동쪽에 있는"],
        ["peace", "평화, 평온함"],
        ["fortune", "부, 재산 / 운"],
        ["accident", "사고 / 우연(한 사건)"],
        ["humor", "익살스러움"],
        ["wrap", "싸다, 포장하다 / 두르다"],
        ["show up", "나타나다, 모습을 드러내다"],
        ["be covered with", "~로 덮여 있다"],
      ],
      [
        ["breathe", "숨 쉬다, 호흡하다"],
        ["gain", "얻다 / 늘다, 쌓다"],
        ["fit", "꼭 맞다 / 적합하다, 어울리다"],
        ["cheif", "최고의, 수석의 / 주요한 / 우두머리"],
        ["humorous", "재미있는"],
        ["unique", "독특한, 특별한 / 유일한, 특유한"],
        ["completely", "완전히, 완벽하게"],
        ["pose", "자세 / 자세를 취하다"],
        ["adventure", "모험"],
        ["tight", "꽉 끼는 / 빡빡한 / 단단히"],
        ["stupid", "어리석은, 우둔한"],
        ["double", "이중의 / 2인용의 / 두 배로 되다"],
        ["race", "경주, 경기 / 인종"],
        ["express", "표현하다, 나타내다"],
        ["illegal", "불법의, 불법적인"],
        ["symbol", "상징(물) / 기호, 부호"],
        ["mention", "(간단히) 말하다, 언급하다"],
        ["sum", "금액 / 합계 / 요약하다"],
        ["look through", "~을 훑어보다"],
        ["throw away", "~을 버리다"],
      ],
      [
        ["bite", "물다 / 한 입, 물린 상처"],
        ["society", "사회 / 협회, 학회, 단체"],
        ["title", "제목, 표제"],
        ["anybody", "누구나, 누구든지 / 누군가 / 아무도"],
        ["fever", "열"],
        ["scenery", "풍경, 경치"],
        ["order", "순서 / 명령하다 / 주문하다"],
        ["neither", "어느 쪽도 ~ 아니다"],
        ["diamond", "마름모꼴"],
        ["source", "원천 / 근원, 원인 / 출처"],
        ["contact", "연락 / 접촉, 맞닿음 / 연락하다"],
        ["equal", "동일한, 같은 / 평등한 / 같다, ~이다"],
        ["none", "아무도 ~않다"],
        ["period", "기간 / 시대"],
        ["journey", "여행"],
        ["rough", "거친 / 대강의 / 힘든"],
        ["million", "100만 / 다수"],
        ["ceiling", "천장"],
        ["give up", "포기하다, 그만두다"],
        ["hang out with", "~와 어울리다, ~와 함께 다니다"],
      ],
      [
        ["hug", "껴안다, 포옹하다 / 껴안기, 포옹"],
        ["vision", "시력 / 전망"],
        ["century", "1세기, 100년"],
        ["anywhere", "어디든지 / 어딘가에 / 아무 데도"],
        ["nearly", "거의"],
        ["beard", "턱수염"],
        ["surround", "둘러싸다, 에워싸다"],
        ["upper", "더 위의, 위쪽의"],
        ["dynasty", "왕조, 시대"],
        ["whole", "전체의, 모든 / 전체, 전부"],
        ["follow", "따라가다 / 뒤를 잇다 / 따르다"],
        ["effort", "노력, 수고"],
        ["imagine", "상상하다"],
        ["shot", "발사 / 슛"],
        ["pimple", "여드름, 뾰루지"],
        ["raindrop", "빗방울"],
        ["ghost", "유령, 귀신"],
        ["sweat", "땀 / 땀을 흘리다"],
        ["care for", "~을 돌보다 / ~을 좋아하다"],
        ["make up", "이루다, 구성하다 / 지어내다"],
      ],
    ],
  },
  {
    title: "Grammar Zone 동사 시제 변화 132제",
    template: "tense",
    timelimit: 20,
    test: {
      all: 24,
      step: 10,
    },
    steps: [
      [
        ["깨우다", "awake", "awoke", "awoken"],
        ["~이다, 있다", "be", "was, were", "been"],
        ["낳다, 견디다", "bear", "bore", "bore, borne"],
        ["치다", "beat", "beat", "beaten"],
        ["되다", "become", "became", "become"],
        ["시작하다", "begin", "began", "begun"],
        ["구부리다", "bend", "bent", "bent"],
        ["내기하다", "bet", "bet", "bet"],
        ["물다", "bite", "bit", "bitten"],
        ["피 흘리다", "bleed", "bled", "bled"],
        ["불다", "blow", "blew", "blown"],
      ],
      [
        ["깨다", "break", "broke", "broken"],
        ["가져오다", "bring", "brought", "brought"],
        ["세우다", "build", "built", "built"],
        ["타다", "burn", "burnt, burned", "burnt, burned"],
        ["터지다", "burst", "burst", "burst"],
        ["사다", "buy", "bought", "bought"],
        ["잡다", "catch", "caught", "caught"],
        ["선택하다", "choose", "chose", "chosen"],
        ["오다", "come", "came", "come"],
        ["비용이 들다", "cost", "cost", "cost"],
        ["자르다", "cut", "cut", "cut"],
      ],
      [
        ["다루다", "deal", "dealt", "dealt"],
        ["뛰어들다", "dive", "dived, dove", "dived"],
        ["하다", "do", "did", "done"],
        ["그리다, 끌다", "draw", "drew", "drawn"],
        ["꿈꾸다", "dream", "dreamt, dreamed", "dreamt, dreamed"],
        ["마시다", "drink", "drank", "drunk"],
        ["운전하다", "drive", "drove", "driven"],
        ["먹다", "eat", "ate", "eaten"],
        ["떨어지다", "fall", "fell", "fallen"],
        ["먹이다", "feed", "fed", "fed"],
        ["느끼다", "feel", "felt", "felt"],
      ],
      [
        ["싸우다", "fight", "fought", "fought"],
        ["발견하다", "find", "found", "found"],
        ["꼭 맞다", "fit", "fit", "fit"],
        ["날다", "fly", "flew", "flown"],
        ["금하다", "forbid", "forbade, forbad", "forbidden"],
        ["잊다", "forget", "fotgot", "forgotten"],
        ["용서하다", "forgive", "forgave", "forgiven"],
        ["얼다", "freeze", "froze", "frozen"],
        ["얻다", "get", "got", "got, gotten"],
        ["주다", "give", "gave", "given"],
        ["가다", "go", "went", "gone"],
      ],
      [
        ["자라다", "grow", "grew", "grown"],
        ["걸다", "hang", "hung", "hung"],
        ["가지다", "have", "had", "had"],
        ["듣다", "hear", "heard", "heard"],
        ["숨기다", "hide", "hid", "hidden"],
        ["치다", "hit", "hit", "hit"],
        ["잡다", "hold", "held", "held"],
        ["다치게 하다", "hurt", "hurt", "hurt"],
        ["유지하다", "keep", "kept", "kept"],
        ["무릎 꿇다", "kneel", "knelt, kneeled", "knelt, kneeled"],
        ["뜨개질하다", "knit", "knit, knitted", "knit, knitted"],
      ],
      [
        ["알다", "know", "knew", "known"],
        ["놓다", "lay", "laid", "laid"],
        ["이끌다", "lead", "led", "led"],
        ["뛰어오르다", "leap", "leapt, leaped", "leapt, leaped"],
        ["떠나다", "leave", "left", "left"],
        ["빌려주다", "lend", "lent", "lent"],
        ["시키다", "let", "let", "let"],
        ["눕다", "lie", "lay", "lain"],
        ["비추다", "light", "lit, lighted", "lit, lighted"],
        ["잃다", "lose", "lost", "lost"],
        ["만들다", "make", "made", "made"],
      ],
      [
        ["뜻하다", "mean", "meant", "meant"],
        ["만나다", "meet", "met", "met"],
        ["지불하다", "pay", "paid", "paid"],
        ["증명하다", "prove", "proved", "proven, proved"],
        ["놓다, 두다", "put", "put", "put"],
        ["그만두다", "quit", "quit, quitted", "quit, quitted"],
        ["읽다", "read", "read", "read"],
        ["올라타다", "ride", "rode", "ridden"],
        ["소리가 울리다", "ring", "rang", "rung"],
        ["일어나다", "rise", "rose", "risen"],
        ["달리다", "run", "ran", "run"],
      ],
      [
        ["말하다", "say", "said", "said"],
        ["보다", "see", "saw", "seen"],
        ["찾다", "seek", "sought", "sought"],
        ["팔다", "sell", "sold", "sold"],
        ["보내다", "send", "sent", "sent"],
        ["놓다", "set", "set", "set"],
        ["꿰매다", "sew", "sewed", "sewn, sewed"],
        ["흔들다", "shake", "shook", "shaken"],
        ["면도하다", "shave", "shaved", "shaved, shaven"],
        ["빛나다", "shine", "shone", "shone"],
        ["쏘다", "shoot", "shot", "shot"],
      ],
      [
        ["보여주다", "show", "showed", "shown"],
        ["움츠러들다", "shrink", "shrank, shrunk", "shrunk"],
        ["닫다", "shut", "shut", "shut"],
        ["노래하다", "sing", "sang", "sung"],
        ["가라앉다", "sink", "sank", "sunk"],
        ["앉다", "sit", "sat", "sat"],
        ["자다", "sleep", "slept", "slept"],
        ["미끄러지다", "slide", "slid", "slid"],
        ["냄새를 맡다", "smell", "smelt, smelled", "smelt, smelled"],
        ["씨 뿌리다", "sow", "sowed", "sown, sowed"],
        ["말하다", "speak", "spoke", "spoken"],
      ],
      [
        ["속력을 내다", "speed", "sped, speeded", "sped, speeded"],
        ["소비하다", "spend", "spent", "spent"],
        ["엎지르다", "spill", "spilt, spilled", "spilt"],
        ["돌다", "spin", "spun", "spun"],
        ["침을 뱉다", "spit", "spit, spat", "spit, spat"],
        ["쪼개다", "split", "split", "split"],
        ["펴다", "spread", "spread", "spread"],
        ["튀어 오르다", "spring", "sprang, sprung", "sprung"],
        ["서다", "stand", "stood", "stood"],
        ["훔치다", "steal", "stole", "stolen"],
        ["붙이다", "stick", "stuck", "stuck"],
      ],
      [
        ["찌르다", "sting", "stung", "stung"],
        ["치다", "strike", "struck", "struck"],
        ["맹세하다", "swear", "swore", "sworn"],
        ["쓸다", "sweep", "swept", "swept"],
        ["수영하다", "swim", "swam", "swum"],
        ["흔들다", "swing", "swung", "swung"],
        ["잡다", "take", "took", "taken"],
        ["가르치다", "teach", "taught", "taught"],
        ["찢다", "tear", "tore", "torn"],
        ["말하다", "tell", "told", "told"],
        ["생각하다", "think", "thought", "thought"],
      ],
      [
        ["던지다", "throw", "threw", "thrown"],
        ["이해하다", "understand", "understood", "understood"],
        ["뒤엎다", "upset", "upset", "upset"],
        ["잠에서 깨다", "wake", "woke, wake", "woken, waked"],
        ["입다, 닳다", "wear", "wore", "worn"],
        ["엮다", "weave", "wove", "woven"],
        ["울다", "weep", "wept", "wept"],
        ["이기다", "win", "won", "won"],
        ["감다", "wind", "wound", "wound"],
        ["물러나다", "withdraw", "withdrew", "withdrawn"],
        ["쓰다", "write", "wrote", "written"]
      ]
    ]
  }
];
