const wordset = [
  {
    title: "주니어 능률 VOCA 기본 1200제",
    template: "swap",
    timelimit: 20,
    test: {
      all: 0,
      step: 10,
    },
    steps: [
      [
        ["fix", "수리하다, 고치다"],
        ["shade", "그늘"],
        ["bury", "묻다, 매장하다"],
        ["cave", "동굴, 굴"],
        ["useful", "쓸모 있는, 유용한"],
        ["dot", "(동그란) 점"],
        ["copy", "복사(본), 복사하다"],
        ["through", "통과하여, 지나서"],
        ["oven", "오븐"],
        ["lend", "빌려주다"],
        ["moment", "순간, 시점, 잠깐, 잠시"],
        ["wing", "날개"],
        ["neighbor", "이웃"],
        ["piece", "조각, 한 개, 한 장"],
        ["still", "아직도, 여전히"],
        ["twin", "쌍둥이, 쌍둥이의"],
        ["pure", "순수한, 맑은, 깨끗한"],
        ["stage", "단계, 시기, 무대"],
        ["at first", "처음에는"],
        ["put on", "~을 입다"]
      ],
      [
        ["war", "전쟁"],
        ["cash", "현금, 현찰"],
        ["advice", "충고, 조언"],
        ["lead", "안내하다, 지도하다, 이끌다"],
        ["perfect", "완벽한, 꼭 알맞은"],
        ["search", "찾다, 수색하다"],
        ["contest", "대회, 콘테스트"],
        ["display", "전시하다, 진열하다"],
        ["tip", "끝, 팁, 봉사료, 조언"],
        ["borrow", "빌리다"],
        ["sharp", "날카로운, 뾰족한"],
        ["machine", "기계"],
        ["trouble", "어려움, 문제"],
        ["roll", "구르다, 굴리다, 두루마리"],
        ["exit", "출구, 나가다, 퇴장하다"],
        ["proud", "자랑스러워하는, 자랑스러운, 거만한"],
        ["flood", "홍수"],
        ["stamp", "우표, 도장"],
        ["at last", "마침내"],
        ["grow up", "자라다, 성장하다"]
      ],
      [
        ["mix", "섞이다, 섞다"],
        ["healthy", "건강한, 건강에 좋은"],
        ["active", "활동적인, 적극적인"],
        ["dig", "파다"],
        ["simple", "간단한, 단순한"],
        ["view", "경치, 전망, 견해, 의견"],
        ["insect", "곤충"],
        ["sleepy", "졸리는"],
        ["root", "뿌리, 근원, 원인"],
        ["total", "총, 전체의, 완전한, 전적인, 합계"],
        ["final", "마지막의, 최후의, 결승"],
        ["scene", "장면, 경치, 풍경"],
        ["prize", "상, 상품"],
        ["nickname", "별명"],
        ["pan", "팬, 프라이팬"],
        ["cartoon", "만화"],
        ["leader", "지도자, 리더"],
        ["coach", "코치, 감독"],
        ["find out", "~을 알아내다"],
        ["be in trouble", "어려움에 처하다"],
      ],
      [
        ["lift", "(들어) 올리다"],
        ["pack", "(짐을) 싸다, 포장하다, 한 갑"],
        ["score", "득점, 점수, 득점하다"],
        ["court", "법정, 법원, 경기장, 코트"],
        ["desert", "사막"],
        ["award", "상, 수여하다, 주다"],
        ["elder", "나이가 더 많은, 노인"],
        ["among", "~ 사이에, ~에 둘러싸여, ~ 중에"],
        ["male", "남성, 수컷"],
        ["finally", "마침내, 결국, 마지막으로"],
        ["sometime", "언젠가"],
        ["rule", "규칙, 규정, 지배하다"],
        ["harmony", "조화, 화합, 화음"],
        ["bark", "짖다"],
        ["crash", "충돌하다, 충돌, 추락"],
        ["nature", "자연, 천성, 본성"],
        ["valley", "계속, 골짜기"],
        ["wonder", "궁금하다, 경탄, 놀라움"],
        ["think up", "~을 생각해내다"],
        ["be famous for", "~로 유명하다"],
      ],
    ]
  },
  {
    title: "Grammar Zone 동사 시제 변화 132제",
    template: "tense",
    timelimit: 20,
    test: {
      all: 24,
      step: 10,
    },
    steps: [
      [
        ["깨우다", "awake", "awoke", "awoken"],
        ["~이다, 있다", "be", "was, were", "been"],
        ["낳다, 견디다", "bear", "bore", "bore, borne"],
        ["치다", "beat", "beat", "beaten"],
        ["되다", "become", "became", "become"],
        ["시작하다", "begin", "began", "begun"],
        ["구부리다", "bend", "bent", "bent"],
        ["내기하다", "bet", "bet", "bet"],
        ["물다", "bite", "bit", "bitten"],
        ["피 흘리다", "bleed", "bled", "bled"],
        ["불다", "blow", "blew", "blown"],
      ],
      [
        ["깨다", "break", "broke", "broken"],
        ["가져오다", "bring", "brought", "brought"],
        ["세우다", "build", "built", "built"],
        ["타다", "burn", "burnt, burned", "burnt, burned"],
        ["터지다", "burst", "burst", "burst"],
        ["사다", "buy", "bought", "bought"],
        ["잡다", "catch", "caught", "caught"],
        ["선택하다", "choose", "chose", "chosen"],
        ["오다", "come", "came", "come"],
        ["비용이 들다", "cost", "cost", "cost"],
        ["자르다", "cut", "cut", "cut"],
      ],
      [
        ["다루다", "deal", "dealt", "dealt"],
        ["뛰어들다", "dive", "dived, dove", "dived"],
        ["하다", "do", "did", "done"],
        ["그리다, 끌다", "draw", "drew", "drawn"],
        ["꿈꾸다", "dream", "dreamt, dreamed", "dreamt, dreamed"],
        ["마시다", "drink", "drank", "drunk"],
        ["운전하다", "drive", "drove", "driven"],
        ["먹다", "eat", "ate", "eaten"],
        ["떨어지다", "fall", "fell", "fallen"],
        ["먹이다", "feed", "fed", "fed"],
        ["느끼다", "feel", "felt", "felt"],
      ],
      [
        ["싸우다", "fight", "fought", "fought"],
        ["발견하다", "find", "found", "found"],
        ["꼭 맞다", "fit", "fit", "fit"],
        ["날다", "fly", "flew", "flown"],
        ["금하다", "forbid", "forbade, forbad", "forbidden"],
        ["잊다", "forget", "fotgot", "forgotten"],
        ["용서하다", "forgive", "forgave", "forgiven"],
        ["얼다", "freeze", "froze", "frozen"],
        ["얻다", "get", "got", "got, gotten"],
        ["주다", "give", "gave", "given"],
        ["가다", "go", "went", "gone"],
      ],
      [
        ["자라다", "grow", "grew", "grown"],
        ["걸다", "hang", "hung", "hung"],
        ["가지다", "have", "had", "had"],
        ["듣다", "hear", "heard", "heard"],
        ["숨기다", "hide", "hid", "hidden"],
        ["치다", "hit", "hit", "hit"],
        ["잡다", "hold", "held", "held"],
        ["다치게 하다", "hurt", "hurt", "hurt"],
        ["유지하다", "keep", "kept", "kept"],
        ["무릎 꿇다", "kneel", "knelt, kneeled", "knelt, kneeled"],
        ["뜨개질하다", "knit", "knit, knitted", "knit, knitted"],
      ],
      [
        ["알다", "know", "knew", "known"],
        ["놓다", "lay", "laid", "laid"],
        ["이끌다", "lead", "led", "led"],
        ["뛰어오르다", "leap", "leapt, leaped", "leapt, leaped"],
        ["떠나다", "leave", "left", "left"],
        ["빌려주다", "lend", "lent", "lent"],
        ["시키다", "let", "let", "let"],
        ["눕다", "lie", "lay", "lain"],
        ["비추다", "light", "lit, lighted", "lit, lighted"],
        ["잃다", "lose", "lost", "lost"],
        ["만들다", "make", "made", "made"],
      ],
      [
        ["뜻하다", "mean", "meant", "meant"],
        ["만나다", "meet", "met", "met"],
        ["지불하다", "pay", "paid", "paid"],
        ["증명하다", "prove", "proved", "proven, proved"],
        ["놓다, 두다", "put", "put", "put"],
        ["그만두다", "quit", "quit, quitted", "quit, quitted"],
        ["읽다", "read", "read", "read"],
        ["올라타다", "ride", "rode", "ridden"],
        ["소리가 울리다", "ring", "rang", "rung"],
        ["일어나다", "rise", "rose", "risen"],
        ["달리다", "run", "ran", "run"],
      ],
      [
        ["말하다", "say", "said", "said"],
        ["보다", "see", "saw", "seen"],
        ["찾다", "seek", "sought", "sought"],
        ["팔다", "sell", "sold", "sold"],
        ["보내다", "send", "sent", "sent"],
        ["놓다", "set", "set", "set"],
        ["꿰매다", "sew", "sewed", "sewn, sewed"],
        ["흔들다", "shake", "shook", "shaken"],
        ["면도하다", "shave", "shaved", "shaved, shaven"],
        ["빛나다", "shine", "shone", "shone"],
        ["쏘다", "shoot", "shot", "shot"],
      ],
      [
        ["보여주다", "show", "showed", "shown"],
        ["움츠러들다", "shrink", "shrank, shrunk", "shrunk"],
        ["닫다", "shut", "shut", "shut"],
        ["노래하다", "sing", "sang", "sung"],
        ["가라앉다", "sink", "sank", "sunk"],
        ["앉다", "sit", "sat", "sat"],
        ["자다", "sleep", "slept", "slept"],
        ["미끄러지다", "slide", "slid", "slid"],
        ["냄새를 맡다", "smell", "smelt, smelled", "smelt, smelled"],
        ["씨 뿌리다", "sow", "sowed", "sown, sowed"],
        ["말하다", "speak", "spoke", "spoken"],
      ],
      [
        ["속력을 내다", "speed", "sped, speeded", "sped, speeded"],
        ["소비하다", "spend", "spent", "spent"],
        ["엎지르다", "spill", "spilt, spilled", "spilt"],
        ["돌다", "spin", "spun", "spun"],
        ["침을 뱉다", "spit", "spit, spat", "spit, spat"],
        ["쪼개다", "split", "split", "split"],
        ["펴다", "spread", "spread", "spread"],
        ["튀어 오르다", "spring", "sprang, sprung", "sprung"],
        ["서다", "stand", "stood", "stood"],
        ["훔치다", "steal", "stole", "stolen"],
        ["붙이다", "stick", "stuck", "stuck"],
      ],
      [
        ["찌르다", "sting", "stung", "stung"],
        ["치다", "strike", "struck", "struck"],
        ["맹세하다", "swear", "swore", "sworn"],
        ["쓸다", "sweep", "swept", "swept"],
        ["수영하다", "swim", "swam", "swum"],
        ["흔들다", "swing", "swung", "swung"],
        ["잡다", "take", "took", "taken"],
        ["가르치다", "teach", "taught", "taught"],
        ["찢다", "tear", "tore", "torn"],
        ["말하다", "tell", "told", "told"],
        ["생각하다", "think", "thought", "thought"],
      ],
      [
        ["던지다", "throw", "threw", "thrown"],
        ["이해하다", "understand", "understood", "understood"],
        ["뒤엎다", "upset", "upset", "upset"],
        ["잠에서 깨다", "wake", "woke, wake", "woken, waked"],
        ["입다, 닳다", "wear", "wore", "worn"],
        ["엮다", "weave", "wove", "woven"],
        ["울다", "weep", "wept", "wept"],
        ["이기다", "win", "won", "won"],
        ["감다", "wind", "wound", "wound"],
        ["물러나다", "withdraw", "withdrew", "withdrawn"],
        ["쓰다", "write", "wrote", "written"]
      ]
    ]
  }
];
